name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: make install-deps
      
    - name: Install pecl
      run: sudo apt-get install php-pear
      
    - name: Installation of ast
      run: pecl install ast

    - name: Pre-commit check
      run: make pre-commit


