name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer install

    - name: Lint check
      run: make lint

    - name: Style Lint check
      run: make stylelint

    - name: Php Lint check
      run: make php-lint


