name: PHP / JavaScript CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:

    - name: Check out nextcloud/server
      uses: actions/checkout@v2
      with:
        repository: nextcloud/server
        ref: stable18

    - name: Checkout app
      uses: actions/checkout@v2
      with:
        path: server/app/skeleton_app
        clean: false

    - name: Get composer cache directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: make install-deps
      working-directory: server/app/skeleton_app

    - name: Adding pecl extension ast
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: pecl
        extensions: ast

    - name: Pre-commit check
      run: make pre-commit
      working-directory: server/app/skeleton_app


