name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: make install-deps
      
    - name: Adding Pecl extension ast
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: pecl
        extensions: ast

    - name: Pre-commit check
      run: make pre-commit


