name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check out to another repo
      uses: actions/checkout@v2
      with:
          repository: nextcloud/server
          ref: stable18
          path: server/app/skeleton_app
          
    - name: Install dependencies
      run: make install-deps
      
    - name: Adding pecl extension ast
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: pecl
        extensions: ast

    - name: Pre-commit check
      run: make pre-commit


